### PR TITLE
Issue 15: Implement TRF estimations across runs and subjects

### LINKED ISSUE #15: Implement TRF estimations across runs and subjects
Following up on issue #10. We were able to estimate TRFs in source space and sensor space on an example subject using a single run. We would now like to estimate TRFs across all the runs that the subject performed, to obtain a single TRF per subject and regressor type (rather one TRF per subject and run). We would also like to estimate these TRFs for all subjects in the dataset, using a batch script that will automate the computation across subjects, and save the results on disk.

This issue tracks the work needed to get all the above working

### PR DESCRIPTION
**Pull request by cedricfoucault**
This PR resolves #15.

- Create a module for TRF estimation, which contains functions for the construction and the estimation of TRF models at the subject-level.
- Add a script to estimate the TRFs for all subjects for a given set of events (trf_estimate_allsubs.py), along with another script that performs this estimation for a single example subject (trf_estimate_example_allruns.py).

In the process of making this change, I've also added some function definitions in coinsmeg_data.py to construct the paths for MEG data files for given subjects and runs, and map event names to event codes.

### CODE REVIEW

**Comment by cedricfoucault** [comment]
I'll update the path to the parc_raw.fif according to the changes made in #19

**Comment by lhuntneuro** [comment]
General suggestion: do we prefer to save the outputs of the TRF estimation as .npy files, or alternatively .npz (where we can store multiple TRFs with different time-axes), pandas files or perhaps [MNE Evoked objects](https://mne.tools/stable/generated/mne.Evoked.html#mne.Evoked)?

My default assumption would be the latter would be the best, if possible - we generally want to store meta-data like what the sensors/sources are, time-axis information, etc alongside the responses, and .fif file format with an Evoked object feels like the natural way to do this. But we would want to see if it can accommodate:
- variable time axes for different TRFs (e.g. the duration of the TRF may be different for stimulus-locked and response-locked TRFs)
- storage of metadata about the TRF estimation - at least names of regressors, but perhaps also storing the design matrix, how it was regularised during estimation, etc

**Comment by cedricfoucault** [comment]
@lhuntneuro I've now encapsulated the results of the TRF estimation in mne.Evoked objects that contain meta-data (.info) including information about channels (sensors/sources) and times, and saved them as .fif files.

**Review by amyxli — APPROVED** [review]
This is amazing, thank you Cedric!

**Review by lhuntneuro — APPROVED** [review]
This is really nice, and good to have the integration with the .fif files. It would be helpful (in future) to have varying time-axes for different regressors in the design matrix, but we probably want to open this as a new issue - would you be able to add this as a separate issue @cedricfoucault ?

**Pull request merged**
